### ISSUE TITLE
Missing slick-pg_upickle-json artifact

### ISSUE THREAD

**Issue by hagerf** [tminglei/slick-pg#761]
I'm trying to use this upickle addon, but sbt is complaining that `slick-pg_upickle-json` does not exist, and indeed when I check on maven repository, I cannot find it there, https://mvnrepository.com/artifact/com.github.tminglei 

Seems to me like that artifact has not been released, which I assume is an oversight.

**Comment by tminglei** [comment]
@hagerf `slick-pg_upickle-json` was missed to release. Sorry!
I have released it just now, pls check again.

**Comment by hagerf** [comment]
Hi @tminglei 
Thanks for looking into it, but I still don't see it. SBT can't find it and I the link I sent above to mvn repository it's still not listed. Right now I've solved this issue by copying the code from the repo, but a package would be nicer to use of course

**Comment by tminglei** [comment]
@hagerf it's [there](https://central.sonatype.com/search?q=slick-pg_upickle-json), you can check it again.

**Comment by hagerf** [comment]
ah, you're right, thanks. I had an error in the name of the package so SBT failed. But now I tried and it worked. So thanks. 

Any chance you could also release it for older versions? I unfortunately I'm stuck to use 0.20.4 for a little while

**Comment by tminglei** [comment]
But, there wasn't upickle json when slick-pg v0.20.4 was released, which was added later than that.

**Comment by hagerf** [comment]
Aha, well I guess I'll have to continue as current until I upgrade then. Thanks again
